version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www
    networks:
      - laravel-network

  php:
    image: munna-php
    container_name: php
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./public:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - nginx
  
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    tty: true
    ports: 
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - laravel-network
    depends_on:
      - php
  
  supervisor:
    image: munna-supervisor
    container_name: supervisor
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/supervisor/Dockerfile
    networks:
      - laravel-network
    volumes:
      - ./public:/var/www
    depends_on:
      - mysql

networks:
  laravel-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local